[package]
name = "guessing_game"
version = "0.1.0"
authors = ["yagi <hiro.yagi0245@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.1.0"
rand = "0.5.5"